steps:
  - name: 'gcr.io/cloud-builders/gcloud'  # Use the official gcloud builder image
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        gcloud compute scp --recurse /workspace ftwomicroinstance:~/deploymentscripts/ --zone=asia-south1-a --tunnel-through-iap --force-key-file-overwrite --strict-host-key-checking=no
        gcloud compute ssh ftwomicroinstance --zone=asia-south1-a --project jmc-devsecops --command 'pwd' --tunnel-through-iap --force-key-file-overwrite --strict-host-key-checking=no
        pwd



