apiVersion: v1
kind: Service
annotations:
    cloud.google.com/neg: '{"ingress": true}'  # Enables internal load balancing
    networking.gke.io/load-balancer-type: "Internal"  # Specifies internal load balancer
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hello-world.selectorLabels" . | nindent 4 }}
